services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8080:80
    image: app:svelte
    container_name: svelte-container
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M